### ISSUE TITLE
Error on Sponge Plugin Reload

### ISSUE THREAD

**Issue by ThornsOfire** [connorhartley/guardian#25]
Environment:

  Sponge version: spongevanilla-1.12.2-7.1.0-BETA-59
  Minecraft version: 1.12.2
  Forge version: N/A

  Guardian version: guardian-7.1.0-1.0.0.bleeding.1
  Precogs version: Precogs-1.2

  Vanilla plugins: [00:38:13 INFO]: Plugins (71): Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, ActiveTime, Animations, AntiBot for Sponge, AntiWDL, AntiXray, Buycraft, CarrotShop, CatClearLag, Chest Refill, ClearChat, CmdBuilder, CmdControl, CmdScheduler, CommandSigns Reloaded, CommandUtils, Composer, CraftBook, CubeEngine - ChopChop, CubeEngine - LibCube, CubeEngine - Spawner, CustomRestartMessage, DailyRewards, Eagle Factions, EasyScoreboards, Entity Disguise, GameKow, GameSpleef, Guardian AntiCheat, HelpMe Advanced, Holograms, HologramsPlus, IPLog, LanDiscovery, LangSwitch, LuckPerms, MagiBridge, MineReset, NPCs, Nucleus, ObsidianBreaker, ParticleEffectCombinator, PetBlocks, PixelBuiltQuests, PlaceholderAPI, PlotSquared, Precogs, ProjectCore, ProjectInventories, ProjectPortals, ProjectWorlds, RankUpper, ServerListPlus, SignEditor, SleepVote, SmoofyDungeon, TabCompleteMagic, TabManager, TimeWarp, TitleMOTD, Total Economy, UltimateChat, Universe Guard 2, VillagerShops, WalletDrop, WorldEdit, blockyarena, spark

  Forge mods: N/A

Report:

  Error on "/Sponge plugins reload"

  Steps to reproduce:
    - run "/Sponge Plugins reload"

[00:34:40 ERROR] [Sponge]: Could not pass GameReloadEvent$Impl to Plugin{id=guardian, name=Guardian AntiCheat, version=7.1.0-1.0.0.bleeding.1, description=An extensible anticheat plugin for Sponge., url=https://github.com/ichorpowered, authors=[Vectrix (Connor Hartley)], source=mods\guardian-7.1.0-1.0.0.bleeding.1.jar}
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_171]
        at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_171]
        at com.ichorpowered.guardian.sponge.feature.CheckFeature.register(CheckFeature.java:87) ~[CheckFeature.class:?]
        at com.ichorpowered.guardian.sponge.GuardianImpl.loadDetections(GuardianImpl.java:78) ~[GuardianImpl.class:?]
        at com.ichorpowered.guardian.sponge.GuardianPlugin.onGameReload(GuardianPlugin.java:127) ~[GuardianPlugin.class:?]
        at org.spongepowered.common.event.listener.GameReloadEventListener_GuardianPlugin_onGameReload136.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) ~[SpongeImpl.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$7(SpongeCommandFactory.java:519) ~[SpongeCommandFactory.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) [ChildCommandElementExecutor.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) [CommandSpec.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) [SimpleDispatcher.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-7.1.0-BETA-59]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:382) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:350) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by vectrixdevelops** [comment]
Sent you a build to test on the Discord server. Let me know if this fixes it. 😄

**Comment by ThornsOfire** [comment]
This error wes on first server start after original bug on reload.


[01:16:03 INFO] [guardian]: Environment [ Platform: SpongeVanilla 1.12.2-7.1.0-BETA-59, Minecraft: 1.12.2 ]
[01:16:03 ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=guardian, name=Guardian AntiCheat, version=7.1.0-1.0.0.bleeding.1, description=An extensible anticheat plugin for Sponge., url=https://github.com/ichorpowered, authors=[Vectrix (Connor Hartley)], source=mods\guardian-7.1.0-1.0.0.bleeding.1.jar}
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_171]
        at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_171]
        at com.ichorpowered.guardian.sponge.feature.CheckFeature.register(CheckFeature.java:87) ~[CheckFeature.class:?]
        at com.ichorpowered.guardian.sponge.GuardianImpl.loadDetections(GuardianImpl.java:78) ~[GuardianImpl.class:?]
        at com.ichorpowered.guardian.sponge.GuardianPlugin.onGameInitialization(GuardianPlugin.java:98) ~[GuardianPlugin.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_GuardianPlugin_onGameInitialization135.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) [SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) [SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:223) [SpongeImpl.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:145) [SpongeVanilla.class:1.12.2-7.1.0-BETA-59]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$bal000(SourceFile:1243) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by ThornsOfire** [comment]
On sponge plugins reload with new bleeding version from discord :P

[01:26:53 WARN] [Sponge]: Plugin guardian attempted to register an already registered listener (com.ichorpowered.guardian.sponge.sequence.SequenceListener)
[01:26:53 ERROR] [STDERR]: java.lang.Exception: Stack trace
[01:26:53 ERROR] [STDERR]:      at java.lang.Thread.dumpStack(Unknown Source)
[01:26:53 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:224)
[01:26:53 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:309)
[01:26:53 ERROR] [STDERR]:      at com.ichorpowered.guardian.sponge.GuardianImpl.startSequence(GuardianImpl.java:87)
[01:26:53 ERROR] [STDERR]:      at com.ichorpowered.guardian.sponge.GuardianPlugin.onGameReload(GuardianPlugin.java:128)
[01:26:53 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameReloadEventListener_GuardianPlugin_onGameReload134.handle(Unknown Source)
[01:26:53 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[01:26:53 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$7(SpongeCommandFactory.java:519)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341)
[01:26:54 ERROR] [STDERR]:      at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328)
[01:26:54 ERROR] [STDERR]:      at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[01:26:54 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:382)
[01:26:54 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:350)
[01:26:54 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560)
[01:26:54 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:464)
[01:26:54 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by ThornsOfire** [comment]
No error on server reboot with new bleeding version.

**Comment by vectrixdevelops** [comment]
I assume this is fixed now? 😄

**Comment by ThornsOfire** [comment]
Yep all good now!
